#:kivy 2.3.1

<ExperienceEditorScreen>:
    MDBoxLayout:
        orientation: "vertical"
        padding: "24dp"
        spacing: "16dp"

        MDLabel:
            text: "Experience Editor"
            halign: "center"
            font_style: "H5"

        MDTextField:
            id: experience_text
            hint_text: "Experience entries"
            multiline: True
            max_height: "200dp"

        MDRectangleFlatButton:
            text: "Back to Profile Editor"
            on_release: root.back_to_profile_editor()
